# Define the gui strings
app_title_string = "Blocknet AIO monitor"
tooltip_howtouse = (f"\n{app_title_string}\n"
                    "HOW TO USE:\n"
                    "1/ (Optional) Set a custom path for the Blocknet core chain directory, or use the default path.\n"
                    "2/ (Optional) Obtain the bootstrap for a faster initial synchronization of the Core wallet.\n"
                    "3/ Start Blocknet Core, wait for it to synchronize with the network, and unlock it.\n"
                    "4/ Start Block-DX.\n"
                    "5/ Start Xlite, create a wallet, and carefully backup the mnemonic.\n")

tooltip_blocknet_core_label_msg = "Blocknet Core is used to connect Xbridge to P2P network and expose it locally"
tooltip_blockdx_label_msg = "Block-DX is a GUI for Xbridge API"
tooltip_xlite_label_msg = "The XLite wallet allows you to manage a variety of digital assets in a single, noncustodial, lightweight, decentralized wallet. Compatible with Xbridge"

blocknet_frame_title_string = "Blocknet Core Management:"
blockdx_frame_title_string = " Block-DX Management:"
xlite_frame_title_string = "XLite Management:"
start_string = "Start"
close_string = "Close"
download_string = "Download"
check_config_string = "Check Config"
blocknet_set_custom_path_string = "Set Custom Path"
blocknet_valid_config_string = "Blocknet Config\nFound"
blocknet_not_valid_config_string = "Blocknet Config Not Found.\nClick Start to Initialize"
blocknet_active_rpc_string = "RPC Connection\nActive"
blocknet_inactive_rpc_string = "RPC Connection\nInactive"
blocknet_data_path_created_string = "Data Path folder\ncreated"
blocknet_data_path_notfound_string = "Data path folder\nnot created"
blocknet_running_string = "Blocknet Process\nrunning"
blocknet_not_running_string = "Blocknet Process\nnot running"
blockdx_running_string = "Block-DX Process\nrunning"
blockdx_not_running_string = "Block-DX Process\nnot running"
blockdx_valid_config_string = "Block-DX Config\nFound & Blocknet RPC Active"
blockdx_not_valid_config_string = "Block-DX Config Not Found.\nClick Start to Initialize"
blockdx_missing_blocknet_config_string = "Block-DX need\nActive Blocknet RPC"
xlite_running_string = "XLite Process\nrunning"
xlite_not_running_string = "XLite Process\nnot running"
xlite_valid_config_string = "XLite Config\nFound"
xlite_not_valid_config_string = "XLite Config\nNot Found"
xlite_daemon_running_string = "XLite-daemon Process\nrunning"
xlite_daemon_not_running_string = "XLite-daemon Process\nnot running"
xlite_daemon_valid_config_string = "XLite-daemon Config\nFound"
xlite_daemon_not_valid_config_string = "XLite-daemon Config\nNot Found"
xlite_reverse_proxy_not_running_string = "XLite-reverse-proxy\nProcess not running"
xlite_store_password_string = "Store Password"
xlite_stored_password_string = "Password Stored"