"""Centralized timing, retry, and network constants.

Split from gui/constants.py: utilities/ must not depend on gui/.
"""

# Button UX
TIME_DISABLE_BUTTON_MS = 3000

# Polling intervals
INTERVAL_PROCESS_CHECK_MS = 5000
INTERVAL_UI_POLL_MS = 1000
INTERVAL_FILE_QUEUE_MS = 100
INTERVAL_AIO_FALLBACK_MS = 2000
INTERVAL_BOTS_POLL_MS = 2000
INTERVAL_BOTS_RETRY_MS = 1000

# Delays
DELAY_ENOSPC_HINT_MS = 1500
DELAY_LAUNCH_CHECK_FAST_MS = 1500
DELAY_LAUNCH_CHECK_SLOW_MS = 4000

# Bots setup retry
MAX_BOTS_RETRY = 30

# File watching
POLLING_OBSERVER_TIMEOUT_S = 2.0
FILE_WATCHER_DEBOUNCE_S = 5.0

# Network
RPC_TIMEOUT_S = 10
GIT_COMMAND_TIMEOUT_S = 300
DOWNLOAD_CHUNK_SIZE = 8192
